gui:
  language: "ja"
  nerdFontsVersion: "3"
  showNumstatInFilesView: true
  showDivergenceFromBaseBranch: arrowAndNumber
git:
  pagers:
    - colorArg: always
      pager: delta --dark --paging=never
    - colorArg: always
      pager: delta --dark --paging=never --side-by-side
  log:
    showWholeGraph: true
