[[mgr.prepend_keymap]]
on   = "<Enter>"
run  = "plugin smart-enter"
desc = "Enter directory or open file"

[[mgr.prepend_keymap]]
on   = "<Esc>"
run  = "escape --all"
desc = "Escape and clear state"

[[input.prepend_keymap]]
on   = "<Esc>"
run  = "close"
desc = "Cancel input"

[[mgr.prepend_keymap]]
on   = "<C-o>"
run  = "shell --orphan -- code %h"
desc = "Open hovered item in VS Code"

[[mgr.prepend_keymap]]
on   = "1"
run  = "plugin smart-switch 0"
desc = "Switch or create tab 1"

[[mgr.prepend_keymap]]
on   = "2"
run  = "plugin smart-switch 1"
desc = "Switch or create tab 2"

[[mgr.prepend_keymap]]
on   = "3"
run  = "plugin smart-switch 2"
desc = "Switch or create tab 3"

[[mgr.prepend_keymap]]
on   = "4"
run  = "plugin smart-switch 3"
desc = "Switch or create tab 4"

[[mgr.prepend_keymap]]
on   = "5"
run  = "plugin smart-switch 4"
desc = "Switch or create tab 5"

[[mgr.prepend_keymap]]
on   = [ "g", "h" ]
run  = "cd ~"
desc = "Go home"

[[mgr.prepend_keymap]]
on   = [ "g", "q" ]
run  = "cd ~/ghq/github.com"
desc = "Go ghq root"

[[mgr.prepend_keymap]]
on   = [ "g", "r" ]
run  = "plugin git-root"
desc = "Go git root"
